### ISSUE TITLE
[BUG] Rocks outside Myrwatch entrance 'clipping' with the stone stairs

### ISSUE THREAD

**Issue by wojsku** [The-Animonculory/AVO-AE#1]
[plugins.txt](https://github.com/The-Animonculory/AVO-AE/files/10373201/plugins.txt)

**Describe the bug**
Rocks outside Myrwatch entrance 'clipping' with the stone stairs. Screenshot attached. Probably following mod is needed: [Myrwatch Majestic Mountains Landscape Patch](https://www.nexusmods.com/skyrimspecialedition/mods/23594)

**To Reproduce**
Go and stand on the stone stairs outside Myrwatch tower.

**Expected behavior**
No clipping.

**Screenshots**
![SkyrimSE 2023-01-08 23-14-08](https://user-images.githubusercontent.com/59418705/211310119-3b800c1b-a518-4792-bdb3-3221b0ad9453.jpeg)

**Modlist version**
AVO-AE V3.1.1

**Did you add any additional mods?**
No, I did not.

**Comment by Althro** [comment]
Thanks for the report, I'll look into getting this sorted for the next update.

**Comment by Althro** [comment]
Fixed in V3.2
