### ISSUE TITLE
Survival Mode Improved - skse : permanently enables survival mode

### ISSUE THREAD

**Issue by billpatterson** [The-Animonculory/AVO-AE#2]
This seems a questionable inclusion for a "visual overhaul" list. This mod not only mucks with survival mode (gameplay change) but also prevents normal/vanilla interaction of skyrim as to it being an optional feature. 

Further, it really messes with the ability to extend from AVO-AE as a base, which is a stated intent of the list.

Specifically, it really screws up any attempt to add the Requiem mod on top of the list default. Requiem uses mechanics that are an alternative to the (optional) bethesda Survival Mode, and "Survival mode improved - SKSE" has to be removed/disabled in order to get Requiem to even work right. Turning on survival mode makes things go wonky with carry weight and other requiem behavors (see: Do Not Go Gentle modlist discord comments, re: "my carry weight is zero", a modlist built by extending AVO).

Please consider removing this survival-mode-forced-on mod/behavior, or making activation optional, as it doesn't fit with the intent of the modlist (in my opinion).

**Comment by Althro** [comment]
No.

**Comment by billpatterson** [comment]
Ok. Fair enough. Seems a bad decision, but it's your list.

**Comment by Althro** [comment]
This is not a bug and more of a "choice" per se. It's really not hard to disable and, if modifying, is something that you should know to do. I will meet you in the middle though. I will note it in the readme that it is present. Then it's down to the user if they want to enable/disable it.

**Comment by billpatterson** [comment]
I appreciate that. I spent several hours of my life debugging only finfaly figure out through trial and error that my "visual overhaul" base set contained something very not related to visuals that was affecting core gameplay mechanics. I didn't think to even look for it, because, hey, AVO is "just a visual overhaul."

**Comment by Althro** [comment]
I've made the change to the readme. With version 3, I don't market AVO as a visuals only list anymore. It now says it's  "designed as a list to bring the vanilla game up to modern standards without changing the core vanilla feel and gameplay."
