### ISSUE TITLE
reshade-shaders-master.zip fails verification

### ISSUE THREAD

**Issue by mjohnson9** [The-Animonculory/AVO-AE#3]
The modlist attempts to download reshade-shaders-master from https://github.com/crosire/reshade-shaders/archive/master.zip. However, that repository seems to have restructured.

It took me quite some searching, but the commit referred to by the modpack is crosire/reshade-shaders/commit@a2314cbf9a6c96de4d434b2f9ab8fa9265b8e575. The permalink to the archive for that commit is: https://github.com/crosire/reshade-shaders/archive/a2314cbf9a6c96de4d434b2f9ab8fa9265b8e575.zip

**Comment by YaroslavMelnychenko** [comment]
@mjohnson9 
I have the same problem, were you able to solve it? I tried downloading manually but it doesn't help.

**Comment by Althro** [comment]
Please join the animonculory discord for a mirror to the file.

**Comment by mjohnson9** [comment]
> @mjohnson9 I have the same problem, were you able to solve it? I tried downloading manually but it doesn't help.

You can download it from the final link in my comment (https://github.com/crosire/reshade-shaders/archive/a2314cbf9a6c96de4d434b2f9ab8fa9265b8e575.zip), and then place the resulting file in the `downloads` folder named `reshade-shaders-master.zip`.

I don't know why anyone would want to join or sign up for Discord as the exclusive means to find such information. It seems to be a frustrating trend in the Skyrim modding scene.

**Comment by Althro** [comment]
The discord is the official support setup for this list. Support is not officially provided via Github.

**Comment by YaroslavMelnychenko** [comment]
@Althro 
But it is a bug. Issues on github was created for bug fixing purposes, wasn't it? 
So we are discussing here a solution to this problem (temporary) until you just close this problem, but make a new release to fix this bug.

**Comment by YaroslavMelnychenko** [comment]
And since you posted the code on github, why should I join the discord to report a bug?
