### ISSUE TITLE
Unable to download reshade-shaders-master.zip

### ISSUE THREAD

**Issue by Smohkin** [The-Animonculory/AVO-AE#4]
Unable to download reshade-shaders-master.zip (HTTPDownloader=State|https:github.com/crosier/reshade-shaders/archive/master.zip)

**Comment by SebastianOpperman** [comment]
This worked for me:
https://drive.google.com/file/d/15RT3YdcG4vUgK_lHqU1pM0L3JHL_2dU_/view
